FROM nginx:alpine

# Устанавливаем переменные окружения для nginx
ENV NGINX_PORT=80

# Копируем файлы Mini App
COPY mini-app /usr/share/nginx/html
COPY nginx/mini-app.conf /etc/nginx/conf.d/default.conf

# Создаем директорию для кеша
RUN mkdir -p /var/cache/nginx && \
    chown -R nginx:nginx /var/cache/nginx && \
    chown -R nginx:nginx /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]